# Generated by Django 3.2.5 on 2021-07-22 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='album',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='store.album'),
        ),
    ]
