# Generated by Django 3.2.5 on 2021-07-27 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_booking_album'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name': 'album'},
        ),
        migrations.RemoveField(
            model_name='booking',
            name='album',
        ),
        migrations.CreateModel(
            name='BookingLines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='store.album')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.booking')),
            ],
        ),
    ]
