# Generated by Django 3.2.5 on 2021-07-27 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20210727_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinglines',
            old_name='contact',
            new_name='booking_id',
        ),
    ]
