# Generated by Django 3.2.5 on 2021-07-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_contact_bookinglines_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookinglines',
            old_name='booking_id',
            new_name='booking',
        ),
    ]
